import os, sys, time, colorama
from time import sleep
from colorama import Fore
print (Fore.BLUE+" Welcome To The Lazy Install Center, ")
print (Fore.RED+" Make Yourself Welcome. ")
time.sleep(1)
print (Fore.RED+" 88                                               ")
time.sleep(0.3)
print (Fore.RED+" 88                                               ")
time.sleep(0.3)
print (Fore.RED+" 88                                               ")
time.sleep(0.3)
print (Fore.RED+" 88           ,adPPYYba,  888888888  8b       d8  ")
time.sleep(0.3)
print (Fore.RED+" 88           ""     `Y8       a8P"  `8b     d8'  ") 
time.sleep(0.3)
print (Fore.RED+" 88           ,adPPPPP88    ,d8P'     `8b   d8'   ")  
time.sleep(0.3) 
print (Fore.RED+" 88           88,    ,88  ,d8"         `8b,d8'    ")    
time.sleep(0.3)
print (Fore.RED+" 88888888888  `"8bbdP"Y8  888888888      Y88'     ")    
time.sleep(0.3)
print (Fore.RED+"                                        d8'       ")      
time.sleep(0.3)
print (Fore.RED+"                                       d8'        ")     
time.sleep(0.3)
os.system(' clear ')
time.sleep(0.3)
print (Fore.MAGENTA+" [01]> Information Gathering ")
time.sleep(0.3)
print (Fore.YELLOW+" [02]> Vulnerability Scan     ")
time.sleep(0.3)
print (Fore.MAGENTA+" [03]> Stress Test           ")
time.sleep(0.3)
print (Fore.YELLOW+" [04]> Websploit              ")
time.sleep(0.3)
lazy = (Fore.MAGENTA+" Lazy ==>> ")